disabled_rules:
  - nesting
  - type_name
  - todo
  - conditional_binding_cascade

excluded:
  - Pods

type_body_length:
  warning: 800
  error: 1000

file_length:
  warning: 800
  error: 1000

line_length:
  warning: 100

closing_brace: error
colon: error
comma: error
control_statement: error
force_unwrapping: error
leading_space: error
legacy_cggeometry_functions: error
legacy_constant: error
legacy_constructor: error
opening_brace: error
operator_whitespace: error
return_arrow_whitespace: error
statement_position: error
trailing_newline: error
trailing_semicolon: error
trailing_whitespace: error
